name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  anchor_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: metadaoproject/anchor-test@v1.3
        with:
          anchor-version: '0.29.0'
          solana-cli-version: '1.16.20'
          node-version: '16.15.1'
          features: 'anchor-test'
      - run: cargo fmt -- --check && cargo clippy