name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  anchor_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3.7.0
        with:
          node-version: '16.20.0'
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml
      - run: pnpm i --frozen-lockfile
      - uses: metadaoproject/anchor-test@v2
        with:
          anchor-version: '0.29.0'
          solana-cli-version: '1.16.20'
          node-version: '16.15.1'
          features: 'anchor-test'
      - run: cargo fmt -- --check && cargo clippy
